title: Your title
description: "Blog description"
keywords: "Some, Key, Words"
url: http://themeideologia.github.com
baseurl: ""
image: assets/img/social-share.png
content: /assets/content

# Build settings
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/page/:num"
permalink   : /:year/:month/:title/
markdown    : kramdown
highlighter : rouge
gems        : [jekyll-paginate]
sass:
  style: compressed

# Repository GitHub
repo: http://github.com/lucasmahle

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]